/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.PoupancaControle;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import modelo.PoupancaEmBanco;

/**
 *
 * @author Felipe
 */
public class Sisbank extends javax.swing.JFrame {
    PoupancaEmBanco peb = new PoupancaEmBanco();
    PoupancaControle pCTRL = new PoupancaControle();    

    /**
     * Creates new form BancoTEDS
     */
    public Sisbank() {
        initComponents();
        dispose();
        setUndecorated(true);
        setVisible(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();  
  
        Point where = new Point(  
        (screenSize.width - this.getWidth()) / 2,  
        (screenSize.height - this.getHeight()) / 2);
        // centraliza a window  
        this.setLocation(where);
        
        bt_addPEB.setEnabled(true);
        bt_editPEB.setEnabled(false);
        bt_excluirPEB.setEnabled(false);
        bt_attPEB.setEnabled(false);
        bt_movPEB.setEnabled(false);
        pCTRL.listarPEB();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_pesq = new javax.swing.JLabel();
        jTextField_Pesq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Cliente = new javax.swing.JLabel();
        jTextField_Cliente = new javax.swing.JTextField();
        jLabel_Banco = new javax.swing.JLabel();
        jComboBox_Banco = new javax.swing.JComboBox();
        jLabel_Agencia = new javax.swing.JLabel();
        jTextField_Agencia = new javax.swing.JTextField();
        jLabel_NP = new javax.swing.JLabel();
        jTextField_NP = new javax.swing.JTextField();
        jLabel_JM = new javax.swing.JLabel();
        jLabel_Saldo = new javax.swing.JLabel();
        jTextField_Saldo = new javax.swing.JTextField();
        jTextField_JM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel_TA = new javax.swing.JLabel();
        jTextField_TA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bt_addPEB = new javax.swing.JButton();
        bt_editPEB = new javax.swing.JButton();
        bt_excluirPEB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Taxa = new javax.swing.JLabel();
        jTextField_Taxa = new javax.swing.JTextField();
        jLabel_NPoup = new javax.swing.JLabel();
        jTextField_NPoup = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bt_attPEB = new javax.swing.JButton();
        bt_movPEB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel_oper = new javax.swing.JLabel();
        jComboBox_oper = new javax.swing.JComboBox();
        jLabel_valor = new javax.swing.JLabel();
        jTextField_valor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel_pesq.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel_pesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_lupa.png"))); // NOI18N
        jLabel_pesq.setText("PESQUISAR:");

        jTextField_Pesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_PesqKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_sair.png"))); // NOI18N
        jLabel1.setText("SAIR");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel_Cliente.setText("Cliente:");

        jLabel_Banco.setText("Banco:");

        jComboBox_Banco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Banco do Brasil", "Banestes", "Bradesco", "Caixa Econômica", "Itaú", "Santander" }));

        jLabel_Agencia.setText("Agência:");
        jLabel_Agencia.setToolTipText("");

        jLabel_NP.setText("Nº. Poupança:");

        jLabel_JM.setText("Juros Mês:");

        jLabel_Saldo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Saldo.setText("SALDO:");

        jTextField_Saldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField_JM.setToolTipText("");

        jLabel4.setText("%");

        jLabel_TA.setText("Taxa Adm.:");

        jTextField_TA.setToolTipText("");

        jLabel5.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Cliente)
                    .addComponent(jLabel_Banco)
                    .addComponent(jLabel_Agencia)
                    .addComponent(jLabel_Saldo))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_Agencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_NP)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_NP))
                    .addComponent(jTextField_Cliente)
                    .addComponent(jComboBox_Banco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_JM)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_JM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_TA)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_TA, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cliente)
                    .addComponent(jTextField_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Banco)
                    .addComponent(jComboBox_Banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Agencia)
                    .addComponent(jTextField_Agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NP)
                    .addComponent(jTextField_NP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_JM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel_JM)
                        .addComponent(jLabel_TA))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Saldo)
                        .addComponent(jTextField_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_TA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_addPEB.setBackground(new java.awt.Color(153, 255, 153));
        bt_addPEB.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bt_addPEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/poup1.png"))); // NOI18N
        bt_addPEB.setText(" ADICIONAR POUPANÇA");
        bt_addPEB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_addPEB.setPreferredSize(new java.awt.Dimension(118, 60));
        bt_addPEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addPEBActionPerformed(evt);
            }
        });

        bt_editPEB.setBackground(new java.awt.Color(255, 255, 153));
        bt_editPEB.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bt_editPEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/poup2.png"))); // NOI18N
        bt_editPEB.setText("  ALTERAR POUPANÇA");
        bt_editPEB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_editPEB.setPreferredSize(new java.awt.Dimension(130, 60));
        bt_editPEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editPEBActionPerformed(evt);
            }
        });

        bt_excluirPEB.setBackground(new java.awt.Color(255, 153, 153));
        bt_excluirPEB.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bt_excluirPEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/poup3.png"))); // NOI18N
        bt_excluirPEB.setText("  EXCLUIR POUPANÇA");
        bt_excluirPEB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_excluirPEB.setPreferredSize(new java.awt.Dimension(130, 60));
        bt_excluirPEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirPEBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SISBANK");

        jLabel3.setText("Versão 1.0");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel_Taxa.setText("Taxa de Juros:");

        jLabel_NPoup.setText("Nº. Poupança:");

        jTextField_NPoup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_NPoupKeyReleased(evt);
            }
        });

        jLabel6.setText("%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_NPoup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_NPoup, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Taxa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Taxa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NPoup)
                    .addComponent(jTextField_NPoup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Taxa)
                    .addComponent(jTextField_Taxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_attPEB.setBackground(new java.awt.Color(204, 204, 255));
        bt_attPEB.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bt_attPEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/poup4.png"))); // NOI18N
        bt_attPEB.setText("   ATUALIZAR SALDO");
        bt_attPEB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_attPEB.setPreferredSize(new java.awt.Dimension(130, 60));
        bt_attPEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_attPEBActionPerformed(evt);
            }
        });

        bt_movPEB.setBackground(new java.awt.Color(153, 153, 153));
        bt_movPEB.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bt_movPEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/poup5.png"))); // NOI18N
        bt_movPEB.setText("   MOVIMENTAÇÃO");
        bt_movPEB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_movPEB.setPreferredSize(new java.awt.Dimension(130, 60));
        bt_movPEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_movPEBActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel_oper.setText("Operação:");

        jComboBox_oper.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "1-Depósito", "2-Saque", "3-Aplicar Juros" }));

        jLabel_valor.setText("Valor:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_oper)
                .addGap(29, 29, 29)
                .addComponent(jComboBox_oper, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_valor)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_oper)
                    .addComponent(jComboBox_oper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_valor)
                    .addComponent(jTextField_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/historico.png"))); // NOI18N
        jLabel7.setText("HISTÓRICO");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_pesq)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_movPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_editPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_addPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_excluirPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_attPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_addPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_excluirPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_attPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_movPEB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pesq)
                    .addComponent(jTextField_Pesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if(evt.getClickCount()==2){
            try {    
                bt_addPEB.setEnabled(false);
                bt_editPEB.setEnabled(true);
                bt_excluirPEB.setEnabled(true);
                bt_attPEB.setEnabled(true);
                bt_movPEB.setEnabled(true);

                limpar();                
                
                jTextField_Cliente.setText((String) jTable.getValueAt(jTable.getSelectedRow(), 1));
                jComboBox_Banco.setSelectedItem((String) jTable.getValueAt(jTable.getSelectedRow(), 2));
                jTextField_Agencia.setText((String) jTable.getValueAt(jTable.getSelectedRow(), 3));
                jTextField_NP.setText(Integer.toString((Integer) jTable.getValueAt(jTable.getSelectedRow(), 4)));
                jTextField_Saldo.setText(Float.toString((Float) jTable.getValueAt(jTable.getSelectedRow(), 5)));       
                jTextField_JM.setText(Float.toString((Float) jTable.getValueAt(jTable.getSelectedRow(), 6)));
                jTextField_TA.setText(Float.toString((Float) jTable.getValueAt(jTable.getSelectedRow(), 7)));
                
                peb.setId((int) jTable.getValueAt(jTable.getSelectedRow(), 0));
                
                inserir();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERRO AO RECUPERAR DADOS DA TABELA", "SISTEDS", JOptionPane.ERROR_MESSAGE);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTableMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int confirm = JOptionPane.showOptionDialog(null,"DESEJA SAIR DO SISTEMA?", "SISTEDS", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();}
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void bt_addPEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addPEBActionPerformed
            if(!jTextField_Cliente.getText().equals("")&&!jTextField_Agencia.getText().equals("")&&!jTextField_NP.getText().equals("")&&!jTextField_Saldo.getText().equals("")&&!jTextField_JM.getText().equals("")&&!jTextField_TA.getText().equals("")&&!jComboBox_Banco.getSelectedItem().equals("Selecione")){
                inserir();
                try{

                    pCTRL.salvar(peb);

                    pCTRL.listarPEB();

                    limpar();

                    JOptionPane.showMessageDialog(null," NOVA POUPANÇA ADICIONADA ", "SISTEDS", JOptionPane.INFORMATION_MESSAGE);
                
                    bt_addPEB.setEnabled(true);
                    bt_editPEB.setEnabled(false);
                    bt_excluirPEB.setEnabled(false);
                    bt_attPEB.setEnabled(false);
                    bt_movPEB.setEnabled(false);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null," ERRO ", "SISTEDS", JOptionPane.ERROR_MESSAGE);
                }}

                else{JOptionPane.showMessageDialog(null, "INSIRA TODOS OS DADOS CORRETAMENTE", "SISTEDS", JOptionPane.WARNING_MESSAGE);
                }
            // TODO add your handling code here:
    }//GEN-LAST:event_bt_addPEBActionPerformed

    private void bt_editPEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editPEBActionPerformed
            if(!jTextField_Cliente.getText().equals("")&&!jTextField_Agencia.getText().equals("")&&!jTextField_NP.getText().equals("")&&!jTextField_Saldo.getText().equals("")&&!jTextField_JM.getText().equals("")&&!jTextField_TA.getText().equals("")&&!jComboBox_Banco.getSelectedItem().equals("Selecione")){
                inserir();
                int confirm = JOptionPane.showOptionDialog(null,"DESEJA SALVAR OS DADOS EDITADOS DA POUPANÇA?", "CONFIRMAÇÃO DE EDIÇÃO", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (confirm == JOptionPane.YES_OPTION){
                    try{

                        pCTRL.editar(peb);

                        pCTRL.listarPEB();

                        limpar();

                        JOptionPane.showMessageDialog(null," DADOS DA POUPANÇA EDITADOS ", "SICONAT-COPS", JOptionPane.INFORMATION_MESSAGE);

                        bt_addPEB.setEnabled(true);
                        bt_editPEB.setEnabled(false);
                        bt_excluirPEB.setEnabled(false);
                        bt_attPEB.setEnabled(false);
                        bt_movPEB.setEnabled(false);
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null," ERRO ", "SICONAT-COPS", JOptionPane.ERROR_MESSAGE);
                    }}}

                    else{JOptionPane.showMessageDialog(null, "INSIRA TODOS OS DADOS CORRETAMENTE", "SISTEDS", JOptionPane.WARNING_MESSAGE);
                    }
                // TODO add your handling code here:
    }//GEN-LAST:event_bt_editPEBActionPerformed

    private void bt_excluirPEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirPEBActionPerformed
        int confirm = JOptionPane.showOptionDialog(null,"DESEJA EXCLUIR OS DADOS DA POUPANÇA?", "CONFIRMAÇÃO DE EDIÇÃO", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == JOptionPane.YES_OPTION){
            try{
                
                pCTRL.excluir(peb);

                pCTRL.listarPEB();

                limpar();

                JOptionPane.showMessageDialog(null," DADOS DA POUPANÇA EXCLUÍDOS ", "SISTEDS", JOptionPane.INFORMATION_MESSAGE);

                    bt_addPEB.setEnabled(true);
                    bt_editPEB.setEnabled(false);
                    bt_excluirPEB.setEnabled(false);
                    bt_attPEB.setEnabled(false);
                    bt_movPEB.setEnabled(false);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null," ERRO ", "SISTEDS", JOptionPane.ERROR_MESSAGE);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_bt_excluirPEBActionPerformed

    private void jTextField_PesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PesqKeyReleased
        pCTRL.pesquisar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PesqKeyReleased

    private void bt_attPEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_attPEBActionPerformed
        try{
            
        if(!jTextField_NPoup.getText().equals("")&&!jTextField_Taxa.getText().equals("")){
            pCTRL.atualizaSaldo(Integer.parseInt((String) jTextField_NPoup.getText()), Float.parseFloat((String) jTextField_Taxa.getText()));
            pCTRL.listarPEB();
                    jTextField_NPoup.setText("");
                    jTextField_Taxa.setText("");
                    bt_addPEB.setEnabled(true);
                    bt_editPEB.setEnabled(false);
                    bt_excluirPEB.setEnabled(false);
                    bt_attPEB.setEnabled(false);
                    bt_movPEB.setEnabled(false);
            JOptionPane.showMessageDialog(null," DADOS ATUALIZADOS COM SUCESSO ", "SISTEDS", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!jTextField_Taxa.getText().equals("")){
            pCTRL.atualizaSaldo(Float.parseFloat((String) jTextField_Taxa.getText()),peb);
            pCTRL.listarPEB();
                    jTextField_NPoup.setText("");
                    jTextField_Taxa.setText("");
                    bt_addPEB.setEnabled(true);
                    bt_editPEB.setEnabled(false);
                    bt_excluirPEB.setEnabled(false);
                    bt_attPEB.setEnabled(false);
                    bt_movPEB.setEnabled(false);
            JOptionPane.showMessageDialog(null," DADOS ATUALIZADOS COM SUCESSO ", "SISTEDS", JOptionPane.INFORMATION_MESSAGE);
        }    
        else if(jTextField_NPoup.getText().equals("")&&jTextField_Taxa.getText().equals("")){
            pCTRL.atualizaSaldo(peb);
            pCTRL.listarPEB();
                    jTextField_NPoup.setText("");
                    jTextField_Taxa.setText("");
                    bt_addPEB.setEnabled(true);
                    bt_editPEB.setEnabled(false);
                    bt_excluirPEB.setEnabled(false);
                    bt_attPEB.setEnabled(false);
                    bt_movPEB.setEnabled(false);
            JOptionPane.showMessageDialog(null," DADOS ATUALIZADOS COM SUCESSO ", "SISTEDS", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "INSIRA TODOS OS DADOS CORRETAMENTE", "SISTEDS", JOptionPane.WARNING_MESSAGE);
        }
        limpar();
        }catch(Exception e){
                JOptionPane.showMessageDialog(null," ERRO ", "SISTEDS", JOptionPane.ERROR_MESSAGE);
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_attPEBActionPerformed

    private void bt_movPEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_movPEBActionPerformed
        try{
        
            if(!jComboBox_oper.getSelectedItem().equals("Selecione")&&!jTextField_valor.getText().equals("")){
                pCTRL.operacao(jComboBox_oper.getSelectedIndex(), Float.parseFloat((String) jTextField_valor.getText()), peb);
                pCTRL.listarPEB();
                    jComboBox_oper.setSelectedIndex(0);
                    jTextField_valor.setText("");
                    bt_addPEB.setEnabled(true);
                    bt_editPEB.setEnabled(false);
                    bt_excluirPEB.setEnabled(false);
                    bt_attPEB.setEnabled(false);
                    bt_movPEB.setEnabled(false);
                JOptionPane.showMessageDialog(null," DADOS ATUALIZADOS COM SUCESSO ", "SISTEDS", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null," INSIRA OS DADOS CORRETAMENTE ", "SISTEDS", JOptionPane.ERROR_MESSAGE);
            }
            limpar();
        }catch(Exception e){
                JOptionPane.showMessageDialog(null," ERRO ", "SISTEDS", JOptionPane.ERROR_MESSAGE);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_movPEBActionPerformed

    private void jTextField_NPoupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NPoupKeyReleased
        if(jTextField_NPoup.getText().length()>=1){
            bt_attPEB.setEnabled(true);
        }else{
            bt_attPEB.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NPoupKeyReleased

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Historico LRframe = new Historico();  
        LRframe.setVisible(true);  
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sisbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sisbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sisbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sisbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sisbank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addPEB;
    private javax.swing.JButton bt_attPEB;
    private javax.swing.JButton bt_editPEB;
    private javax.swing.JButton bt_excluirPEB;
    private javax.swing.JButton bt_movPEB;
    private javax.swing.JComboBox jComboBox_Banco;
    private javax.swing.JComboBox jComboBox_oper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Agencia;
    private javax.swing.JLabel jLabel_Banco;
    private javax.swing.JLabel jLabel_Cliente;
    private javax.swing.JLabel jLabel_JM;
    private javax.swing.JLabel jLabel_NP;
    private javax.swing.JLabel jLabel_NPoup;
    private javax.swing.JLabel jLabel_Saldo;
    private javax.swing.JLabel jLabel_TA;
    private javax.swing.JLabel jLabel_Taxa;
    private javax.swing.JLabel jLabel_oper;
    private javax.swing.JLabel jLabel_pesq;
    private javax.swing.JLabel jLabel_valor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField_Agencia;
    private javax.swing.JTextField jTextField_Cliente;
    private javax.swing.JTextField jTextField_JM;
    private javax.swing.JTextField jTextField_NP;
    private javax.swing.JTextField jTextField_NPoup;
    public static javax.swing.JTextField jTextField_Pesq;
    private javax.swing.JTextField jTextField_Saldo;
    private javax.swing.JTextField jTextField_TA;
    private javax.swing.JTextField jTextField_Taxa;
    private javax.swing.JTextField jTextField_valor;
    // End of variables declaration//GEN-END:variables
    
    public void inserir() {
        peb.setNomeCliente(jTextField_Cliente.getText());
        peb.setNomeBanco(jComboBox_Banco.getSelectedItem().toString());
        peb.setAgencia(jTextField_Agencia.getText());
        peb.setNumPoup(Integer.parseInt((String) jTextField_NP.getText()));
        peb.setSaldo(Float.parseFloat((String) jTextField_Saldo.getText()));
        peb.setJurosMensal(Float.parseFloat((String) jTextField_JM.getText()));
        peb.setTaxaAdm(Float.parseFloat((String) jTextField_TA.getText()));
    }
    public void limpar() {
        jTextField_Cliente.setText(null);
        jComboBox_Banco.setSelectedIndex(0);
        jTextField_Agencia.setText(null);
        jTextField_NP.setText(null);
        jTextField_Saldo.setText(null);        
        jTextField_JM.setText(null);
        jTextField_TA.setText(null);

        peb.setId(null);
        peb.setNomeCliente(null);
        peb.setNomeBanco(null);
        peb.setAgencia(null);
        peb.setNumPoup(null);
        peb.setSaldo(0);
        peb.setJurosMensal(0);
        peb.setTaxaAdm(0);
    }

}
